### source-api ingress / deployed
GET http://localhost:80/weatherforecast
Host: app.source-api.com

### companion-source-api ingress / deployed
GET http://localhost:80/weatherforecast
Host: app.companion-source-api.com

### source-api ingress
GET http://localhost:8803/weatherforecast
Host: app.source-api.com

### companion-source-api ingress
GET http://localhost:8803/weatherforecast
Host: app.companion-source-api.com

### source-api
http://localhost:8803/weatherforecast


### companion-source-api
http://localhost:8800/weatherforecast

### companion-containerized-api
http://localhost:8801/weatherforecast