### A template request. The port value has to be replaced with a real port 
### obtained from Tye dashboard.

http://localhost:52590/weatherforecast


### source-api when port is forwarded

http://localhost:8800/weatherforecast